"""Regenerates the notebooks/*.ipynb files from the cell definitions below, so notebooks stay
regenerable and reviewable in diff (per the implementation plan's notebook-hygiene note).

Usage:
    python notebooks/_build_notebooks.py            # (re)write all notebooks, cells only
    python notebooks/_build_notebooks.py --execute   # also execute each notebook in place

Each `build_XX_*()` function returns an nbformat notebook. Cell 1 of every notebook is a
markdown cell declaring its inputs/outputs per the plan's notebook-hygiene rule.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import nbformat as nbf

_NOTEBOOKS_DIR = Path(__file__).resolve().parent


def md(source: str) -> "nbf.NotebookNode":
    return nbf.v4.new_markdown_cell(source.strip())


def code(source: str) -> "nbf.NotebookNode":
    return nbf.v4.new_code_cell(source.strip("\n"))


_SETUP_CELL = code(
    """
import os, sys
from pathlib import Path

# Notebook hygiene: always run from the v1 root, never hard-code absolute d:\\... paths.
_here = Path.cwd()
_v1_root = _here if (_here / "pyproject.toml").exists() else _here.parents[0]
os.chdir(_v1_root)
sys.path.insert(0, str(_v1_root))

# Notebooks that touch libs.platform.registry/config must pin a profile explicitly, the
# process env has no APP_PROFILE by default, which silently falls back to "cpu" (real Ollama
# calls, no stub) and produces confusing failures/latency. Pin stub here; override the env var
# before importing libs.platform.config in the rare notebook that needs otherwise.
os.environ.setdefault("APP_PROFILE", "stub")
print("cwd:", Path.cwd(), "| APP_PROFILE:", os.environ["APP_PROFILE"])
"""
)


# ---------------------------------------------------------------------------
# 01: data preparation
# ---------------------------------------------------------------------------
def build_01_data_preparation() -> "nbf.NotebookNode":
    cells = [
        md(
            """
# 01, Data preparation

**Inputs:**
- `data/Bitext_Sample_Customer_Support_Training_Dataset_27K_responses-v11.csv.zip`
- `data/telecom_supplement.csv` (generated by `scripts/generate_telecom_supplement.py`, Bitext
  has zero coverage of `network_operations` / `field_service`, so a classifier trained on Bitext
  alone can never predict those two departments)
- `config/department_map.yaml`

**Outputs:**
- `data/raw/*.csv` (extracted Bitext CSV)
- `data/processed/{train,val,test}.csv`
- EDA printed below
"""
        ),
        _SETUP_CELL,
        code(
            """
import re
import zipfile

import pandas as pd
import yaml
from sklearn.model_selection import train_test_split

RANDOM_STATE = 22
"""
        ),
        md("## Extract the Bitext zip to `data/raw/`"),
        code(
            """
raw_dir = Path("data/raw")
raw_dir.mkdir(parents=True, exist_ok=True)

bitext_zip = Path("../data/Bitext_Sample_Customer_Support_Training_Dataset_27K_responses-v11.csv.zip")
with zipfile.ZipFile(bitext_zip) as zf:
    zf.extractall(raw_dir)

bitext_csv = next(raw_dir.glob("*.csv"))
print("extracted:", bitext_csv)
"""
        ),
        md("## Load Bitext + the telecom supplement, EDA on categories/intents"),
        code(
            """
bitext = pd.read_csv(bitext_csv)
telecom = pd.read_csv("data/telecom_supplement.csv")
print("bitext rows:", len(bitext), "| categories:", bitext["category"].nunique(), "| intents:", bitext["intent"].nunique())
print("telecom supplement rows:", len(telecom), "| categories:", sorted(telecom["category"].unique()))
bitext["category"].value_counts()
"""
        ),
        code(
            """
df = pd.concat([bitext, telecom], ignore_index=True)
df.head(3)
"""
        ),
        md(
            """
## Map Bitext `category` -> project `Department`

`ORDER,SHIPPING,DELIVERY -> general`; `REFUND,INVOICE,PAYMENT -> billing`;
`CONTACT,FEEDBACK -> general`; `ACCOUNT,SUBSCRIPTION -> technical_support`; `CANCEL -> retention`;
plus the telecom supplement's `NETWORK -> network_operations`, `FIELDSERVICE -> field_service`.
The mapping is data (`config/department_map.yaml`), not code, so it can be revised without a
notebook change.
"""
        ),
        code(
            """
dept_map = yaml.safe_load(Path("config/department_map.yaml").read_text(encoding="utf-8"))["category_to_department"]
df["department"] = df["category"].map(dept_map)
assert df["department"].isna().sum() == 0, "unmapped category found"
df["department"].value_counts()
"""
        ),
        md(
            """
## Strip templated slots

The `instruction` column contains templated slots like `{{Order Number}}`; if left in, the
classifier learns to key off the literal `{{` / `}}` characters instead of the surrounding
language. Strip them (not randomise, the surrounding phrasing already carries the signal).
"""
        ),
        code(
            """
slot_re = re.compile(r"\\{\\{[^}]*\\}\\}")
df["text"] = df["instruction"].apply(lambda s: slot_re.sub("", s).strip())
df["text"] = df["text"].str.replace(r"\\s+", " ", regex=True)
(df["instruction"].str.contains(slot_re)).sum(), (df["text"].str.contains(slot_re)).sum()
"""
        ),
        md("## Stratified 80/10/10 split by department"),
        code(
            """
train_df, temp_df = train_test_split(df, test_size=0.2, stratify=df["department"], random_state=RANDOM_STATE)
val_df, test_df = train_test_split(temp_df, test_size=0.5, stratify=temp_df["department"], random_state=RANDOM_STATE)

out_dir = Path("data/processed")
out_dir.mkdir(parents=True, exist_ok=True)
train_df[["text", "department", "category", "intent"]].to_csv(out_dir / "train.csv", index=False)
val_df[["text", "department", "category", "intent"]].to_csv(out_dir / "val.csv", index=False)
test_df[["text", "department", "category", "intent"]].to_csv(out_dir / "test.csv", index=False)

len(train_df), len(val_df), len(test_df)
"""
        ),
        code(
            """
import json

metrics_path = Path("evaluation/reports/metrics.jsonl")
metrics_path.parent.mkdir(parents=True, exist_ok=True)
with open(metrics_path, "a", encoding="utf-8") as f:
    f.write(json.dumps({
        "notebook": "01_data_preparation",
        "rows_total": len(df),
        "rows_train": len(train_df),
        "rows_val": len(val_df),
        "rows_test": len(test_df),
        "departments": df["department"].value_counts().to_dict(),
    }) + "\\n")
print("appended metrics row")
"""
        ),
    ]
    nb = nbf.v4.new_notebook()
    nb["cells"] = cells
    return nb


# ---------------------------------------------------------------------------
# 02: department classifier
# ---------------------------------------------------------------------------
def build_02_department_classifier() -> "nbf.NotebookNode":
    cells = [
        md(
            """
# 02, Department classifier

**Inputs:** `data/processed/{train,val,test}.csv` (from notebook 01)

**Outputs:** `models/artifacts/department_clf.joblib` + sidecar `department_clf.json`
(`{model_version, trained_at, classes, macro_f1, threshold}`)

**Acceptance target:** macro-F1 >= 0.85 on the held-out test split.
"""
        ),
        _SETUP_CELL,
        code(
            """
import json
from datetime import datetime, timezone

import joblib
import pandas as pd
from sklearn.calibration import CalibratedClassifierCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import ConfusionMatrixDisplay, classification_report, f1_score
from sklearn.pipeline import FeatureUnion, Pipeline
from sklearn.svm import LinearSVC

RANDOM_STATE = 22

train_df = pd.read_csv("data/processed/train.csv")
val_df = pd.read_csv("data/processed/val.csv")
test_df = pd.read_csv("data/processed/test.csv")
len(train_df), len(val_df), len(test_df)
"""
        ),
        md(
            """
## Features

Word 1-2 grams + char 3-5 grams (the char n-grams help with typos and the templated,
slightly-repetitive phrasing in both data sources).
"""
        ),
        code(
            """
def make_features():
    word_vec = TfidfVectorizer(analyzer="word", ngram_range=(1, 2), min_df=2, sublinear_tf=True)
    char_vec = TfidfVectorizer(analyzer="char_wb", ngram_range=(3, 5), min_df=2, sublinear_tf=True)
    return FeatureUnion([("word", word_vec), ("char", char_vec)])
"""
        ),
        md("## Baseline A: calibrated LinearSVC"),
        code(
            """
svc_pipe = Pipeline([
    ("features", make_features()),
    ("clf", CalibratedClassifierCV(LinearSVC(class_weight="balanced", C=1.0, random_state=RANDOM_STATE), method="sigmoid", cv=3)),
])
svc_pipe.fit(train_df["text"], train_df["department"])
svc_val_pred = svc_pipe.predict(val_df["text"])
svc_macro_f1 = f1_score(val_df["department"], svc_val_pred, average="macro")
print("LinearSVC macro-F1 (val):", svc_macro_f1)
print(classification_report(val_df["department"], svc_val_pred))
"""
        ),
        md("## Baseline B: Logistic Regression"),
        code(
            """
lr_pipe = Pipeline([
    ("features", make_features()),
    ("clf", LogisticRegression(class_weight="balanced", max_iter=1000, random_state=RANDOM_STATE)),
])
lr_pipe.fit(train_df["text"], train_df["department"])
lr_val_pred = lr_pipe.predict(val_df["text"])
lr_macro_f1 = f1_score(val_df["department"], lr_val_pred, average="macro")
print("LogisticRegression macro-F1 (val):", lr_macro_f1)
print(classification_report(val_df["department"], lr_val_pred))
"""
        ),
        md(
            """
## Calibration check

`ClassifierPort` must return usable confidences, the triage priority threshold and the
sklearn->LLM->rules classifier fallback order both depend on them being meaningful, not just a
tie-breaking score.
"""
        ),
        code(
            """
import numpy as np

winner_pipe = svc_pipe if svc_macro_f1 >= lr_macro_f1 else lr_pipe
winner_name = "LinearSVC (calibrated)" if svc_macro_f1 >= lr_macro_f1 else "LogisticRegression"
print("winner:", winner_name)

proba = winner_pipe.predict_proba(val_df["text"])
top1_conf = proba.max(axis=1)
top1_correct = (winner_pipe.classes_[proba.argmax(axis=1)] == val_df["department"].values)

bins = np.linspace(0, 1, 11)
bin_ids = np.digitize(top1_conf, bins) - 1
for b in sorted(set(bin_ids)):
    mask = bin_ids == b
    if mask.sum() == 0:
        continue
    print(f"confidence [{bins[b]:.1f},{bins[b+1] if b+1 < len(bins) else 1.0:.1f}): "
          f"n={mask.sum():4d} accuracy={top1_correct[mask].mean():.3f} mean_conf={top1_conf[mask].mean():.3f}")
"""
        ),
        md("## Final evaluation on the held-out test split"),
        code(
            """
test_pred = winner_pipe.predict(test_df["text"])
test_macro_f1 = f1_score(test_df["department"], test_pred, average="macro")
print("held-out test macro-F1:", test_macro_f1)
print(classification_report(test_df["department"], test_pred))
assert test_macro_f1 >= 0.85, f"macro-F1 {test_macro_f1:.3f} is below the 0.85 acceptance target"
"""
        ),
        code(
            """
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(7, 6))
ConfusionMatrixDisplay.from_predictions(test_df["department"], test_pred, ax=ax, xticks_rotation=45)
fig.tight_layout()
report_dir = Path("evaluation/reports")
report_dir.mkdir(parents=True, exist_ok=True)
fig.savefig(report_dir / "department_classifier_confusion_matrix.png", dpi=120)
print("saved confusion matrix plot")
"""
        ),
        md("## Save the artifact"),
        code(
            """
artifacts_dir = Path("models/artifacts")
artifacts_dir.mkdir(parents=True, exist_ok=True)

model_version = f"department_clf-{datetime.now(timezone.utc):%Y%m%d%H%M%S}"
joblib.dump({"pipeline": winner_pipe}, artifacts_dir / "department_clf.joblib")

sidecar = {
    "model_version": model_version,
    "trained_at": datetime.now(timezone.utc).isoformat(),
    "classes": sorted(winner_pipe.classes_.tolist()),
    "macro_f1": test_macro_f1,
    "threshold": 0.5,
    "winner": winner_name,
}
(artifacts_dir / "department_clf.json").write_text(json.dumps(sidecar, indent=2), encoding="utf-8")
sidecar
"""
        ),
        code(
            """
with open("evaluation/reports/metrics.jsonl", "a", encoding="utf-8") as f:
    f.write(json.dumps({
        "notebook": "02_department_classifier",
        "winner": winner_name,
        "val_macro_f1": svc_macro_f1 if winner_name.startswith("LinearSVC") else lr_macro_f1,
        "test_macro_f1": test_macro_f1,
    }) + "\\n")
print("appended metrics row")
"""
        ),
    ]
    nb = nbf.v4.new_notebook()
    nb["cells"] = cells
    return nb


# ---------------------------------------------------------------------------
# 04: priority and sentiment
# ---------------------------------------------------------------------------
def build_04_priority_and_sentiment() -> "nbf.NotebookNode":
    cells = [
        md(
            """
# 04, Priority weight and sentiment calibration

**Inputs:** none external, v1 has no historical priority-labelled ticket log, so this notebook
generates a synthetic labelled sample from a held-out "true" weight vector plus label noise, to
demonstrate and validate the calibration methodology end to end.

**Outputs:** `config/priority_weights.yaml` (weights only, the domain policy in
`libs/domain/policy/priority.py` stays code; ADR-010).

The domain policy stays code; only the six weights are data. This notebook calibrates the
*weights*, not the scoring formula itself.
"""
        ),
        _SETUP_CELL,
        code(
            """
import random

import yaml
from sklearn.metrics import cohen_kappa_score

from libs.domain.policy.priority import DEFAULT_WEIGHTS, TriageInputs, score

random.seed(22)
SIGNAL_KEYS = ["sentiment", "urgency_keywords", "customer_segment", "outage_scope", "prior_contacts", "sla_age"]
"""
        ),
        md(
            """
## Lexicon-based sentiment baseline

`triage_svc` currently classifies sentiment via a small keyword lexicon (angry/frustrated
markers). Evaluate it against a small hand-labelled sample of representative ticket openers.
"""
        ),
        code(
            """
SENTIMENT_SAMPLES = [
    ("This is absolutely unacceptable, I've called three times about the same issue.", "angry"),
    ("I am furious that no one has fixed this yet.", "angry"),
    ("This is ridiculous, fix it now.", "angry"),
    ("I'm still not getting internet, this is the third time this month.", "frustrated"),
    ("Again my connection dropped, I'm getting annoyed.", "frustrated"),
    ("I've tried the reset again and it's still not working.", "frustrated"),
    ("Hi, could you help me check my internet connection please?", "neutral"),
    ("My router light is red, can you assist?", "neutral"),
    ("Just wanted to ask about upgrading my plan.", "neutral"),
    ("Thanks so much, the technician did a great job yesterday!", "satisfied"),
    ("Really happy with how quickly this got resolved.", "satisfied"),
    ("Great service, appreciate the quick fix.", "satisfied"),
]

_ANGRY_MARKERS = ("angry", "furious", "unacceptable", "ridiculous", "worst", "outrageous")
_FRUSTRATED_MARKERS = ("frustrated", "again", "still not", "third time", "annoyed", "fed up")


def lexicon_sentiment(text: str) -> str:
    lowered = text.lower()
    if any(m in lowered for m in _ANGRY_MARKERS):
        return "angry"
    if any(m in lowered for m in _FRUSTRATED_MARKERS):
        return "frustrated"
    return "neutral"  # the lexicon has no positive-sentiment markers -> "satisfied" is unreachable


preds = [lexicon_sentiment(text) for text, _ in SENTIMENT_SAMPLES]
labels = [label for _, label in SENTIMENT_SAMPLES]
accuracy = sum(p == l for p, l in zip(preds, labels)) / len(labels)
print(f"lexicon sentiment accuracy: {accuracy:.2f}")
list(zip(labels, preds))
"""
        ),
        md(
            """
Result: the lexicon catches angry/frustrated/neutral but has no positive marker list, so
"satisfied" is structurally unreachable, a real limitation to flag in `06-vlm-and-asr.md`'s
sibling doc, `08-evaluation.md`. Fixing it only needs a small positive-marker list; left as a
follow-up rather than scope creep here.
"""
        ),
        md(
            """
## Synthetic labelled priority sample

Generate 200 tickets with random signal values, label them with a held-out "true" weight vector
plus 8% label noise (simulating human disagreement at band boundaries), then treat those labels
as ground truth for calibration, exactly the workflow a real historical-ticket sample would
follow once v1 has been in production long enough to accumulate one.
"""
        ),
        code(
            """
TRUE_WEIGHTS = {
    "sentiment": 30, "urgency_keywords": 15, "customer_segment": 10,
    "outage_scope": 25, "prior_contacts": 5, "sla_age": 15,
}
BAND_ORDER = ["critical", "high", "normal", "low"]


def gen_ticket() -> TriageInputs:
    return {
        "sentiment_score": round(random.random(), 2),
        "urgency_keyword_hit": random.random() < 0.3,
        "customer_segment_score": random.choice([0.3, 1.0]),
        "outage_scope_score": round(random.random(), 2) if random.random() < 0.2 else 0.0,
        "prior_contacts_score": round(random.random(), 2),
        "sla_age_score": round(random.random(), 2),
    }


def true_band(inputs: TriageInputs, noise: float = 0.08) -> str:
    _, band, _ = score(inputs, TRUE_WEIGHTS)
    if random.random() < noise:
        idx = BAND_ORDER.index(band.value)
        idx = max(0, min(len(BAND_ORDER) - 1, idx + random.choice([-1, 1])))
        return BAND_ORDER[idx]
    return band.value


tickets = [gen_ticket() for _ in range(200)]
labels = [true_band(t) for t in tickets]
from collections import Counter
Counter(labels)
"""
        ),
        md(
            """
## Randomised grid search over the weight simplex

A full 6-dimensional integer grid summing to 100 has tens of thousands of points; a full sweep
isn't necessary to demonstrate the calibration methodology, so this samples the simplex (Dirichlet
draw scaled to sum 100) and keeps the best-scoring point. Swap for `itertools.product` over a
coarse per-weight grid if an exhaustive search is ever needed.
"""
        ),
        code(
            """
default_preds = [score(t, DEFAULT_WEIGHTS)[1].value for t in tickets]
default_kappa = cohen_kappa_score(labels, default_preds)
print("default weights kappa:", round(default_kappa, 4))

best_kappa, best_weights = None, None
for _trial in range(800):
    raw = [random.random() for _ in SIGNAL_KEYS]
    total = sum(raw)
    candidate = {k: round(v / total * 100) for k, v in zip(SIGNAL_KEYS, raw)}
    candidate[SIGNAL_KEYS[0]] += 100 - sum(candidate.values())  # fix rounding drift back to 100

    preds = [score(t, candidate)[1].value for t in tickets]
    kappa = cohen_kappa_score(labels, preds)
    if best_kappa is None or kappa > best_kappa:
        best_kappa, best_weights = kappa, candidate

print("calibrated weights kappa:", round(best_kappa, 4))
best_weights
"""
        ),
        md("## Save the calibrated weights"),
        code(
            """
out_path = Path("config/priority_weights.yaml")
out_path.write_text(
    yaml.safe_dump(
        {
            "weights": best_weights,
            "calibration": {
                "method": "randomised simplex search, 800 trials, Cohen's kappa vs synthetic labels",
                "kappa": round(best_kappa, 4),
                "default_weights_kappa": round(default_kappa, 4),
                "sample_size": len(tickets),
            },
        },
        sort_keys=False,
    ),
    encoding="utf-8",
)
print(f"wrote {out_path}")
"""
        ),
        code(
            """
import json

with open("evaluation/reports/metrics.jsonl", "a", encoding="utf-8") as f:
    f.write(json.dumps({
        "notebook": "04_priority_and_sentiment",
        "sentiment_lexicon_accuracy": accuracy,
        "default_weights_kappa": default_kappa,
        "calibrated_weights_kappa": best_kappa,
    }) + "\\n")
print("appended metrics row")
"""
        ),
    ]
    nb = nbf.v4.new_notebook()
    nb["cells"] = cells
    return nb


# ---------------------------------------------------------------------------
# 06: ASR evaluation
# ---------------------------------------------------------------------------
def build_06_asr_evaluation() -> "nbf.NotebookNode":
    cells = [
        md(
            """
# 06, ASR evaluation

**Inputs:** `ingestion-pipeline-prototype/data/sample_audio/{sample_call.wav, audio.mp3}`

**Outputs:** `asr_low_confidence_threshold` recommendation, latency numbers, a plot in
`evaluation/reports/`.

**Known limitation (documented, not worked around):** neither sample audio file has a
human-labelled reference transcript, so a real WER number cannot be computed here, `WER
requires a labelled reference corpus, which v1 does not ship. `sample_call.wav` is a synthetic
tone (see `ingestion-pipeline-prototype/generate_samples.py`), useful as a *negative* control for
confidence calibration; `audio.mp3` is real speech (~11.5 min), useful for latency and confidence
distribution. Getting a real WER number is future work: label a small held-out call sample.
"""
        ),
        _SETUP_CELL,
        code(
            """
import time

from faster_whisper import WhisperModel

AUDIO_DIR = Path("../ingestion-pipeline-prototype/data/sample_audio")
SAMPLES = {"synthetic_tone": AUDIO_DIR / "sample_call.wav", "real_speech": AUDIO_DIR / "audio.mp3"}
MODEL_SIZES = ["tiny", "base"]
"""
        ),
        md("## Transcribe both samples with both model sizes, recording latency and per-segment confidence"),
        code(
            """
import math

results = []
for model_size in MODEL_SIZES:
    t0 = time.time()
    model = WhisperModel(model_size, device="cpu", compute_type="int8")
    load_s = time.time() - t0

    for label, path in SAMPLES.items():
        t0 = time.time()
        segments, info = model.transcribe(str(path), language=None)
        segments = list(segments)
        transcribe_s = time.time() - t0

        confidences = [math.exp(s.avg_logprob) for s in segments]
        results.append({
            "model_size": model_size,
            "sample": label,
            "load_s": load_s,
            "transcribe_s": transcribe_s,
            "duration_s": info.duration,
            "latency_per_audio_minute_s": transcribe_s / (info.duration / 60) if info.duration else float("nan"),
            "num_segments": len(segments),
            "mean_confidence": sum(confidences) / len(confidences) if confidences else 0.0,
            "min_confidence": min(confidences) if confidences else 0.0,
            "max_confidence": max(confidences) if confidences else 0.0,
        })
        print(f"{model_size:5s} {label:15s} duration={info.duration:6.1f}s transcribe={transcribe_s:6.1f}s "
              f"mean_conf={results[-1]['mean_confidence']:.3f}")

import pandas as pd
results_df = pd.DataFrame(results)
results_df
"""
        ),
        md(
            """
## Confidence-based threshold calibration

The synthetic tone should be flagged `LOW_ASR_CONFIDENCE` far more often than the real speech
sample. Sweep candidate thresholds and report the discrimination, the goal (per the
implementation plan) is a threshold where flagged transcripts capture the low-quality sample
without over-flagging the real-speech sample.
"""
        ),
        code(
            """
tiny_model = WhisperModel("tiny", device="cpu", compute_type="int8")

per_segment = []
for label, path in SAMPLES.items():
    segments, _ = tiny_model.transcribe(str(path), language=None)
    for s in segments:
        per_segment.append({"sample": label, "confidence": math.exp(s.avg_logprob)})

seg_df = pd.DataFrame(per_segment)

for threshold in [0.40, 0.50, 0.60, 0.70, 0.80]:
    flagged = seg_df.groupby("sample")["confidence"].apply(lambda c: (c < threshold).mean())
    print(f"threshold={threshold:.2f}  tone_flagged_rate={flagged.get('synthetic_tone', 0):.2f}  "
          f"real_speech_flagged_rate={flagged.get('real_speech', 0):.2f}")
"""
        ),
        code(
            """
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(7, 4))
for label in SAMPLES:
    subset = seg_df[seg_df["sample"] == label]["confidence"]
    ax.hist(subset, bins=20, alpha=0.6, label=label)
ax.axvline(0.60, color="red", linestyle="--", label="candidate threshold 0.60")
ax.set_xlabel("segment confidence (exp(avg_logprob))")
ax.set_ylabel("count")
ax.legend()
fig.tight_layout()

report_dir = Path("evaluation/reports")
report_dir.mkdir(parents=True, exist_ok=True)
fig.savefig(report_dir / "asr_confidence_distribution.png", dpi=120)
print("saved plot")
"""
        ),
        md(
            """
## Recommendation

The synthetic tone produces **zero transcribed segments** at every model size (Whisper's VAD
correctly identifies it as non-speech) rather than low-confidence segments, so the
`LOW_ASR_CONFIDENCE` flag and the "no segments" case are two distinct, both-valid degradation
signals, and `audio_svc` should treat an empty transcript the same way it already treats a
failed transcription (still publish `tickets.audio.done`, just with `status` reflecting no
content). On the real-speech sample, mean confidence is 0.59 (tiny) / 0.68 (base) with a spread
of ~0.33-0.89, comfortably straddling the 0.60 default, so 0.60 is a reasonable starting point,
but this is n=1 real recording, not a statistically robust calibration. Revisit once a labelled
call sample is available.
"""
        ),
        code(
            """
import json

with open("evaluation/reports/metrics.jsonl", "a", encoding="utf-8") as f:
    f.write(json.dumps({
        "notebook": "06_asr_evaluation",
        "results": results,
        "recommended_asr_low_confidence_threshold": 0.60,
        "wer_available": False,
        "wer_limitation": "no labelled reference transcript for either sample audio file",
    }) + "\\n")
print("appended metrics row")
"""
        ),
    ]
    nb = nbf.v4.new_notebook()
    nb["cells"] = cells
    return nb


# ---------------------------------------------------------------------------
# 07: knowledge and GraphRAG
# ---------------------------------------------------------------------------
def build_07_knowledge_and_graphrag() -> "nbf.NotebookNode":
    cells = [
        md(
            """
# 07, Knowledge chunking, embeddings, and GraphRAG

**Inputs:** `config/seed/knowledge/*.md` (the 6 seeded SOPs), `config/seed/graph_seed.yaml`

**Outputs:** chunking-strategy comparison, embedding-model comparison (recall@5, MRR on 40
hand-written question -> chunk pairs), and a dense-only vs dense+graph-expansion comparison on
fault prediction, the experiment that justifies ADR-007 (graph expansion on top of dense
retrieval).

**Substitution note:** the plan calls for MiniLM-L6 vs BGE-small; this environment substitutes
`all-MiniLM-L12-v2` for BGE-small (both ~small, CPU-fast, no gated/large download) so the
comparison methodology runs end to end here. Swap in `BAAI/bge-small-en-v1.5` for a plan-faithful
run where a larger download is acceptable.
"""
        ),
        _SETUP_CELL,
        code(
            """
import numpy as np
from sentence_transformers import SentenceTransformer

from libs.platform.graph.inmemory import InMemoryGraphStore
from services.knowledge_ingest.chunk import heading_aware_chunks
from services.retrieval_svc.handler import _extract_seed_terms

KNOWLEDGE_DIR = Path("config/seed/knowledge")
DOC_PATHS = sorted(KNOWLEDGE_DIR.glob("*.md"))
[p.name for p in DOC_PATHS]
"""
        ),
        md("## Chunking-strategy comparison: fixed 500/800/1200 chars vs heading-aware"),
        code(
            """
def fixed_chunks(text: str, size: int) -> list[str]:
    text = text.strip()
    return [text[i : i + size].strip() for i in range(0, len(text), size) if text[i : i + size].strip()]


rows = []
for path in DOC_PATHS:
    text = path.read_text(encoding="utf-8")
    for strategy, chunks in [
        ("fixed_500", fixed_chunks(text, 500)),
        ("fixed_800", fixed_chunks(text, 800)),
        ("fixed_1200", fixed_chunks(text, 1200)),
        ("heading_aware", heading_aware_chunks(text)),
    ]:
        lengths = [len(c) for c in chunks]
        rows.append({
            "doc": path.stem, "strategy": strategy, "num_chunks": len(chunks),
            "avg_len": sum(lengths) / len(lengths) if lengths else 0,
        })

import pandas as pd
chunking_df = pd.DataFrame(rows)
chunking_df.groupby("strategy")[["num_chunks", "avg_len"]].mean()
"""
        ),
        md(
            """
Heading-aware chunking produces more, shorter chunks than the fixed strategies because it never
merges two `##` sections together, even when both are under the size threshold, e.g. a short
"Symptoms" section becomes its own chunk instead of bleeding into "Diagnosis". This is exactly
the property that makes citations precise (retrieval points at one procedure, not two).
"""
        ),
        md("## Build the real chunk set (heading-aware) and embed with two models"),
        code(
            """
doc_chunks: dict[str, list[str]] = {}
for path in DOC_PATHS:
    doc_chunks[path.stem] = heading_aware_chunks(path.read_text(encoding="utf-8"))

all_chunks = [(doc, i, text) for doc, chunks in doc_chunks.items() for i, text in enumerate(chunks)]
print(f"{len(all_chunks)} chunks across {len(doc_chunks)} documents")

model_a = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
model_b = SentenceTransformer("sentence-transformers/all-MiniLM-L12-v2")

texts = [c[2] for c in all_chunks]
emb_a = model_a.encode(texts, convert_to_numpy=True, normalize_embeddings=True)
emb_b = model_b.encode(texts, convert_to_numpy=True, normalize_embeddings=True)
"""
        ),
        md(
            """
## 40 hand-written question -> chunk pairs

One or more questions per chunk, phrased the way a support agent would actually ask (not just
the section heading reworded), covering all 6 SOPs.
"""
        ),
        code(
            """
# (doc stem, chunk index, question)
QA_PAIRS = [
    ("sop_router_power", 1, "What are the symptoms of a router power issue?"),
    ("sop_router_power", 1, "My router's power LED is blinking red, what does that mean?"),
    ("sop_router_power", 2, "How do I diagnose whether it's a power supply fault?"),
    ("sop_router_power", 3, "How do I power-cycle the router?"),
    ("sop_router_power", 3, "What are the steps to restart the router?"),
    ("sop_router_power", 4, "How do I factory reset the router?"),
    ("sop_router_power", 5, "When should I send a replacement power supply?"),
    ("sop_router_power", 6, "When do I escalate a router power issue to field service?"),
    ("sop_line_sync", 1, "What does it mean if the internet LED is amber?"),
    ("sop_line_sync", 1, "The internet light is off completely, what's wrong?"),
    ("sop_line_sync", 2, "How do I tell if it's a line synchronisation fault?"),
    ("sop_line_sync", 3, "How do I check the WAN cabling?"),
    ("sop_line_sync", 4, "How do I run a remote line diagnostic?"),
    ("sop_line_sync", 4, "What does the run_line_diagnostic action check?"),
    ("sop_line_sync", 5, "When does a line sync issue escalate to network operations?"),
    ("sop_intermittent", 1, "The connection drops for a few seconds at a time, why?"),
    ("sop_intermittent", 1, "Wifi disconnects randomly during the day, what could cause that?"),
    ("sop_intermittent", 2, "How do I figure out if intermittent drops are congestion or cabling?"),
    ("sop_intermittent", 3, "What diagnostic should I run for intermittent connection loss?"),
    ("sop_intermittent", 4, "When should I book a technician for intermittent drops?"),
    ("sop_intermittent", 5, "When does an intermittent connection issue escalate further?"),
    ("sop_billing", 1, "The customer says they were charged twice, what's the process?"),
    ("sop_billing", 1, "A customer was billed after they already cancelled, what do I check?"),
    ("sop_billing", 2, "How do I check if a billing dispute is genuine?"),
    ("sop_billing", 3, "How do I issue a billing credit?"),
    ("sop_billing", 3, "What reason codes are used for billing credits?"),
    ("sop_billing", 4, "The customer says their payment isn't showing, what do I do?"),
    ("sop_billing", 5, "What must I avoid promising in a billing dispute reply?"),
    ("sop_field_service_visit", 1, "When do I schedule a field service visit instead of a remote fix?"),
    ("sop_field_service_visit", 2, "How do I book a technician visit?"),
    ("sop_field_service_visit", 2, "What address details do I need to schedule an engineer visit?"),
    ("sop_field_service_visit", 3, "What happens if a second technician visit is needed within 14 days?"),
    ("sop_account_retention", 1, "A customer wants to cancel their subscription, what should I check first?"),
    ("sop_account_retention", 1, "The customer is threatening to switch providers, what do I do?"),
    ("sop_account_retention", 2, "How do I handle a cancellation request?"),
    ("sop_account_retention", 2, "Can I offer a discount to stop someone cancelling?"),
    ("sop_account_retention", 3, "What must I avoid saying about a cancellation that hasn't been processed?"),
    ("sop_router_power", 0, "What is this document about?"),
    ("sop_line_sync", 0, "What SOP covers line synchronisation problems?"),
    ("sop_billing", 0, "What SOP covers billing disputes?"),
]
len(QA_PAIRS)
"""
        ),
        md("## recall@5 and MRR for each embedding model"),
        code(
            """
chunk_index_lookup = {(doc, i): pos for pos, (doc, i, _) in enumerate(all_chunks)}


def evaluate(embeddings: np.ndarray) -> dict:
    hits_at_5 = 0
    reciprocal_ranks = []
    for doc, chunk_idx, question in QA_PAIRS:
        target_pos = chunk_index_lookup.get((doc, chunk_idx))
        if target_pos is None:
            continue
        q_emb = model_a.encode([question], convert_to_numpy=True, normalize_embeddings=True)[0] \\
            if embeddings is emb_a else model_b.encode([question], convert_to_numpy=True, normalize_embeddings=True)[0]
        sims = embeddings @ q_emb
        ranked = np.argsort(-sims)
        rank = int(np.where(ranked == target_pos)[0][0]) + 1
        hits_at_5 += int(rank <= 5)
        reciprocal_ranks.append(1.0 / rank)

    n = len(QA_PAIRS)
    return {"recall_at_5": hits_at_5 / n, "mrr": sum(reciprocal_ranks) / n}


results_a = evaluate(emb_a)
results_b = evaluate(emb_b)
print("all-MiniLM-L6-v2: ", results_a)
print("all-MiniLM-L12-v2:", results_b)
"""
        ),
        md(
            """
## Dense-only vs dense+graph expansion on fault prediction

For a small set of realistic customer-phrased symptom queries, compare: does the *document* of
the top-1 dense hit correspond to a plausible fault for that symptom, vs does the fault actually
appear as a node when the query's keywords are expanded through the seed graph
(`InMemoryGraphStore.expand`, the mechanism `retrieval_svc` uses in production)?
"""
        ),
        code(
            """
DOC_TO_PLAUSIBLE_FAULTS = {
    "sop_router_power": {"fault_power_supply", "fault_firmware_crashloop", "fault_hardware"},
    "sop_line_sync": {"fault_line_sync", "fault_cabling"},
    "sop_intermittent": {"fault_intermittent_connection"},
    "sop_billing": {"fault_billing_dispute"},
    "sop_field_service_visit": {"fault_hardware", "fault_cabling", "fault_no_dial_tone"},
}

FAULT_QUERIES = [
    ("my router power light is red and wont turn on", "fault_power_supply"),
    ("the router keeps rebooting itself over and over", "fault_firmware_crashloop"),
    ("internet led stuck amber never goes green", "fault_line_sync"),
    ("connection keeps dropping randomly throughout the day", "fault_intermittent_connection"),
    ("i was charged twice on my invoice this month", "fault_billing_dispute"),
    ("wifi drops out every few minutes all afternoon", "fault_intermittent_connection"),
    ("the power light on my modem wont come on at all", "fault_power_supply"),
]

graph_store = InMemoryGraphStore(Path("config/seed/graph_seed.yaml"))
doc_texts = [" ".join(doc_chunks[doc]) for doc in doc_chunks]
doc_names = list(doc_chunks.keys())
doc_embeddings = model_a.encode(doc_texts, convert_to_numpy=True, normalize_embeddings=True)

dense_correct, graph_correct = 0, 0
for query, expected_fault in FAULT_QUERIES:
    q_emb = model_a.encode([query], convert_to_numpy=True, normalize_embeddings=True)[0]
    top_doc = doc_names[int(np.argmax(doc_embeddings @ q_emb))]
    dense_ok = expected_fault in DOC_TO_PLAUSIBLE_FAULTS.get(top_doc, set())
    dense_correct += int(dense_ok)

    seed_terms = _extract_seed_terms(query)
    subgraph = graph_store.expand(seed_terms, hops=2)
    graph_faults = {n["id"] for n in subgraph.nodes if n.get("label") == "Fault"}
    graph_ok = expected_fault in graph_faults
    graph_correct += int(graph_ok)

    print(f"{query!r:60s} expected={expected_fault:28s} dense_top_doc={top_doc:24s} dense_ok={dense_ok!s:5s} graph_ok={graph_ok}")

n = len(FAULT_QUERIES)
print(f"\\ndense-only accuracy: {dense_correct/n:.2f}   dense+graph accuracy: {graph_correct/n:.2f}")
"""
        ),
        md(
            """
**Honest reading of these numbers** (worth stating plainly rather than picking the result that
fits a nicer story): dense-only scores 100% here, not graph. That's because the "dense_ok" metric
is document-level and lenient (does the top-retrieved *document* plausibly contain the expected
fault, out of a per-document candidate set), and with only 6 topically well-separated SOPs, doc
retrieval is an easy task at that granularity.

What the graph actually contributes, and dense-only does not, is **fault-level precision**: for
every symptom-shaped query it resolves, it returns a small, specific candidate set
(`fault_power_supply` + `fault_firmware_crashloop`, not "somewhere in sop_router_power's ~1500
characters"). Its one miss is real and structural, not incidental: `fault_billing_dispute` has no
`LedState`/`Symptom` node feeding it in the seed graph, so keyword-expansion from a billing query
can never reach it, dense retrieval is the only path to billing content. That is the actual
argument for ADR-007's *dense-first, then graph-expand* order: graph narrows dense's output to a
precise fault when the vocabulary lines up with the seed graph, and dense is the fallback (not an
afterthought) for everything the graph has no path to. A same-granularity metric (graph's fault
set vs dense's single nearest chunk mapped to a fault) would be a fairer head-to-head than this
document-level proxy, worth doing once the KB is large enough that document-level retrieval
stops being trivial.
"""
        ),
        code(
            """
import json

with open("evaluation/reports/metrics.jsonl", "a", encoding="utf-8") as f:
    f.write(json.dumps({
        "notebook": "07_knowledge_and_graphrag",
        "chunking_comparison": chunking_df.groupby("strategy")[["num_chunks", "avg_len"]].mean().to_dict(),
        "embedding_all_minilm_l6": results_a,
        "embedding_all_minilm_l12": results_b,
        "dense_only_fault_accuracy": dense_correct / n,
        "dense_plus_graph_fault_accuracy": graph_correct / n,
    }) + "\\n")
print("appended metrics row")
"""
        ),
    ]
    nb = nbf.v4.new_notebook()
    nb["cells"] = cells
    return nb


# ---------------------------------------------------------------------------
# 08: end-to-end evaluation
# ---------------------------------------------------------------------------
def build_08_end_to_end_evaluation() -> "nbf.NotebookNode":
    cells = [
        md(
            """
# 08, End-to-end evaluation

**Inputs:** none external, drives `evaluation/harness/run.py` over 100 synthetic multimodal
tickets, generated by `evaluation/datasets/synthetic.py` and submitted through the exact same
`create_ticket` entrypoint `intake_api` uses (UC-8's "same code, different driver" seam).

**Outputs:** `evaluation/reports/e2e_report.{json,csv,md}`

**Runs under `APP_PROFILE=stub`**, no Ollama server or GPU needed in this environment. This is
the load-bearing caveat for reading the numbers below: `StubGenerator` returns one **fixed**
canned diagnosis (`fault_power_supply`, chunk id `c1`) regardless of the ticket, and
`RuleOnlyClassifier` (not the trained sklearn artifact from notebook 02) is forced for CI
determinism. So this run demonstrates **the metrics pipeline is correct and the full pipeline
completes reliably at throughput**, it is not a measurement of real model quality. Re-run with
`APP_PROFILE=cpu` and Ollama running for numbers that reflect the real LLM/classifier.
"""
        ),
        _SETUP_CELL,
        code(
            """
from pathlib import Path

from evaluation.harness.run import run as run_harness, write_reports

report = run_harness(n=100, database_path=Path("v1_data/harness_nb08.db"), report_dir=Path("evaluation/reports"))
write_reports(report, Path("evaluation/reports"))
report
"""
        ),
        md("## SRS §5.1 stage-latency budget check"),
        code(
            """
for stage, s in report["stage_latency_ms"].items():
    print(f"{stage:30s} p50={s['p50_ms']:8.1f}ms  p95={s['p95_ms']:8.1f}ms  n={s['n']}")
"""
        ),
        md(
            """
## Reading these numbers honestly

- **Completion rate**: 100/100 tickets reached `READY_FOR_AGENT`, the pipeline itself (fusion,
  state machine, degradation paths) is reliable at this scale under the stub profile.
- **Department accuracy/macro-F1**: reflects `RuleOnlyClassifier`, a small keyword table, not
  the notebook 02 sklearn artifact (test macro-F1 1.0 on held-out Bitext+telecom data). The stub
  profile intentionally never touches the filesystem classifier artifact (CI determinism).
- **Fault top-1/top-3 accuracy**: structurally low because `StubGenerator` returns the *same*
  canned fault for every ticket, only tickets whose expected fault happens to match it can
  score. This metric is only meaningful with a real LLM.
- **Citation verification rate**: NaN, `StubGenerator`'s canned citation (`chunk_id="c1"`) never
  matches a real retrieved chunk id, so `orchestrator_svc.verify_citations` drops it every time
  and no diagnosis ever has a *verified* citation to average over. Also only meaningful with a
  real LLM and an ingested knowledge base.
- **Stage latencies** are real and profile-appropriate: `PROCESSING->AGGREGATED` is the slowest
  stage because it's the one bounded by the 120s aggregation window logic (though it resolves
  immediately here since every attachment's stub adapter succeeds) and by SQLite write
  contention across concurrent broker worker threads, see `09-operations.md` for the production
  (Kafka + Postgres) latency expectations this does not capture.
"""
        ),
    ]
    nb = nbf.v4.new_notebook()
    nb["cells"] = cells
    return nb


# ---------------------------------------------------------------------------
# 03: intent and diagnosis LLM (Ollama fine-tune), NOT EXECUTED in this environment
# ---------------------------------------------------------------------------
def build_03_intent_and_diagnosis_llm() -> "nbf.NotebookNode":
    cells = [
        md(
            """
# 03, Intent and diagnosis LLM (the Ollama fine-tune)

**NOT EXECUTED IN THIS ENVIRONMENT.** This sandbox has no running Ollama server, no GPU, and no
Hugging Face auth for the gated `meta-llama/Meta-Llama-3.1-8B-Instruct` weights that Track B
needs. The code below is complete and intended to run as-is on a machine that has those three
things, it is not a stub or placeholder, just unexecuted. See `05-llm-finetuning-ollama.md` for
the full writeup of what running it should produce and how to roll back if it doesn't.

**Inputs:** `data/processed/{train,val,test}.csv` (notebook 01), `models/prompts/llm/diagnosis.txt`

**Outputs:** Track A baseline metrics; Track B a merged, quantised, `ollama create`-registered
model (`cst-diagnosis:v1`) plus `evaluation/reports/llm_comparison.md`.

**Two tracks, run both and compare:**
- **Track A** (no training): prompt engineering + few-shot for `llama3.1:8b-instruct` through
  Ollama, `format: json`. This is the baseline v1 ships with if training fails or is skipped.
- **Track B** (LoRA): QLoRA fine-tune, merge, convert to GGUF, register with Ollama.
"""
        ),
        _SETUP_CELL,
        code(
            """
import json

import pandas as pd

train_df = pd.read_csv("data/processed/train.csv")
val_df = pd.read_csv("data/processed/val.csv")
# `intent` is already a column from notebook 01 (Bitext's 27 intents + the telecom supplement's).
train_df[["text", "department", "intent"]].head()
"""
        ),
        md(
            """
## Building the intent/diagnosis instruction dataset

Bitext's `intent` column plus the telecom supplement's give the `intent` target; `fault` is
only meaningful for the telecom rows (Bitext has no fault concept), Bitext rows get
`fault: null` and `department` doubles as the coarse target for those.
"""
        ),
        code(
            """
_TELECOM_INTENT_TO_FAULT = {
    "no_internet_connection": "fault_power_supply",
    "router_led_issue": "fault_power_supply",
    "slow_internet_speed": "fault_intermittent_connection",
    "intermittent_connection": "fault_intermittent_connection",
    "no_dial_tone": "fault_no_dial_tone",
    "line_synchronization_issue": "fault_line_sync",
    "area_outage_report": "fault_line_sync",
    "schedule_technician_visit": None,
    "missed_technician_appointment": None,
    "equipment_installation_request": None,
    "cabling_issue_onsite": "fault_cabling",
    "technician_visit_status": None,
}

SYSTEM_PROMPT = (
    "You are a telecom customer-support intent and fault classifier. Respond as JSON: "
    '{"intent": str, "fault": str|null, "department": str}'
)


def to_chat_example(row) -> dict:
    fault = _TELECOM_INTENT_TO_FAULT.get(row["intent"])
    return {
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": row["text"]},
            {"role": "assistant", "content": json.dumps({"intent": row["intent"], "fault": fault, "department": row["department"]})},
        ]
    }


train_examples = [to_chat_example(row) for _, row in train_df.iterrows()]
val_examples = [to_chat_example(row) for _, row in val_df.iterrows()]

Path("data/processed").mkdir(parents=True, exist_ok=True)
with open("data/processed/llm_train.jsonl", "w", encoding="utf-8") as f:
    for ex in train_examples:
        f.write(json.dumps(ex) + "\\n")
with open("data/processed/llm_val.jsonl", "w", encoding="utf-8") as f:
    for ex in val_examples:
        f.write(json.dumps(ex) + "\\n")

len(train_examples), len(val_examples)
"""
        ),
        md("## Track A: prompt engineering + few-shot, no training"),
        code(
            """
import httpx

OLLAMA_BASE_URL = "http://localhost:11434"
BASE_MODEL = "llama3.1:8b-instruct-q4_K_M"

FEW_SHOT_EXAMPLES = train_df.sample(6, random_state=22)[["text", "intent", "department"]].to_dict("records")


def build_few_shot_prompt(text: str) -> str:
    shots = "\\n\\n".join(
        f'Ticket: {ex["text"]}\\nJSON: {{"intent": "{ex["intent"]}", "department": "{ex["department"]}"}}'
        for ex in FEW_SHOT_EXAMPLES
    )
    return f"{shots}\\n\\nTicket: {text}\\nJSON:"


def classify_via_ollama(text: str, model: str = BASE_MODEL) -> dict:
    resp = httpx.post(
        f"{OLLAMA_BASE_URL}/api/chat",
        json={
            "model": model,
            "messages": [{"role": "system", "content": SYSTEM_PROMPT}, {"role": "user", "content": build_few_shot_prompt(text)}],
            "format": "json",
            "stream": False,
            "options": {"temperature": 0.1},
        },
        timeout=120.0,
    )
    resp.raise_for_status()
    return json.loads(resp.json()["message"]["content"])


# Evaluate Track A on a held-out sample of the val split.
eval_sample = val_df.sample(min(200, len(val_df)), random_state=22)
track_a_results = []
for _, row in eval_sample.iterrows():
    try:
        parsed = classify_via_ollama(row["text"])
        track_a_results.append({
            "intent_correct": parsed.get("intent") == row["intent"],
            "department_correct": parsed.get("department") == row["department"],
            "json_valid": True,
        })
    except Exception:
        track_a_results.append({"intent_correct": False, "department_correct": False, "json_valid": False})

track_a_df = pd.DataFrame(track_a_results)
track_a_summary = {
    "intent_accuracy": track_a_df["intent_correct"].mean(),
    "department_accuracy": track_a_df["department_correct"].mean(),
    "json_validity_rate": track_a_df["json_valid"].mean(),
}
track_a_summary
"""
        ),
        md(
            """
## Track B: QLoRA fine-tune

4-bit, r=16, alpha=32, lr=2e-4, 2 epochs, batch size 1 x grad-accum 16, max_seq_len=1024.

**Pitfalls (see `docs/00-IMPLEMENTATION-PLAN.md` §9):** needs ~10-12 GB VRAM for the 8B base, if
the GPU is smaller, switch `BASE_MODEL_ID` to `Qwen/Qwen2.5-3B-Instruct` or
`meta-llama/Llama-3.2-3B-Instruct`; the Llama 3.1 weights are gated on Hugging Face (`huggingface-cli
login` and accept the licence first); GGUF conversion needs the **merged** model, not the bare
adapter; `bitsandbytes` on Windows needs a recent wheel, if it won't install, run this notebook
in WSL2 or Colab and copy the resulting GGUF back.
"""
        ),
        code(
            """
BASE_MODEL_ID = "meta-llama/Meta-Llama-3.1-8B-Instruct"  # or a 3B fallback, see pitfalls above
ADAPTER_DIR = Path("models/artifacts/cst-diagnosis-lora")
MERGED_DIR = Path("models/artifacts/cst-diagnosis-merged")
GGUF_PATH = Path("models/artifacts/cst-diagnosis-q4_K_M.gguf")

import torch
from datasets import load_dataset
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, TrainingArguments
from trl import SFTTrainer  # part of the `datasets`/`transformers` ecosystem; add to [train] if missing

tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_ID)
tokenizer.pad_token = tokenizer.pad_token or tokenizer.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True, bnb_4bit_quant_type="nf4", bnb_4bit_compute_dtype=torch.bfloat16, bnb_4bit_use_double_quant=True
)
model = AutoModelForCausalLM.from_pretrained(BASE_MODEL_ID, quantization_config=bnb_config, device_map="auto")
model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=16, lora_alpha=32, lora_dropout=0.05, bias="none", task_type="CAUSAL_LM",
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

train_ds = load_dataset("json", data_files="data/processed/llm_train.jsonl", split="train")
val_ds = load_dataset("json", data_files="data/processed/llm_val.jsonl", split="train")


def format_example(example):
    return {"text": tokenizer.apply_chat_template(example["messages"], tokenize=False)}


train_ds = train_ds.map(format_example)
val_ds = val_ds.map(format_example)

training_args = TrainingArguments(
    output_dir=str(ADAPTER_DIR),
    per_device_train_batch_size=1,
    gradient_accumulation_steps=16,
    num_train_epochs=2,
    learning_rate=2e-4,
    logging_steps=10,
    save_strategy="epoch",
    bf16=True,
    gradient_checkpointing=True, # if OOM on a smaller GPU, per the plan's pitfalls
)

trainer = SFTTrainer(
    model=model, args=training_args, train_dataset=train_ds, eval_dataset=val_ds,
    dataset_text_field="text", max_seq_length=1024,
)
trainer.train()
trainer.model.save_pretrained(ADAPTER_DIR)
tokenizer.save_pretrained(ADAPTER_DIR)
"""
        ),
        md("## Merge, convert to GGUF, quantise, register with Ollama"),
        code(
            """
from peft import PeftModel

base_model = AutoModelForCausalLM.from_pretrained(BASE_MODEL_ID, torch_dtype=torch.bfloat16, device_map="auto")
merged = PeftModel.from_pretrained(base_model, ADAPTER_DIR).merge_and_unload()  # merged, not the bare adapter
merged.save_pretrained(MERGED_DIR)
tokenizer.save_pretrained(MERGED_DIR)
"""
        ),
        code(
            """
# Requires a local llama.cpp checkout with convert_hf_to_gguf.py and the `llama-quantize` binary.
import subprocess

subprocess.run(
    ["python", "llama.cpp/convert_hf_to_gguf.py", str(MERGED_DIR), "--outfile", "models/artifacts/cst-diagnosis-f16.gguf"],
    check=True,
)
subprocess.run(
    ["llama.cpp/llama-quantize", "models/artifacts/cst-diagnosis-f16.gguf", str(GGUF_PATH), "q4_K_M"], check=True
)
"""
        ),
        code(
            """
modelfile = f'''FROM {GGUF_PATH}
TEMPLATE \"\"\"{{{{ if .System }}}}<|start_header_id|>system<|end_header_id|>\\n\\n{{{{ .System }}}}<|eot_id|>{{{{ end }}}}<|start_header_id|>user<|end_header_id|>\\n\\n{{{{ .Prompt }}}}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\\n\\n\"\"\"
PARAMETER temperature 0.2
SYSTEM \"\"\"{SYSTEM_PROMPT}\"\"\"
'''
Path("models/Modelfile").write_text(modelfile, encoding="utf-8")

subprocess.run(["ollama", "create", "cst-diagnosis:v1", "-f", "models/Modelfile"], check=True)
print("registered cst-diagnosis:v1, set llm_model=cst-diagnosis:v1 in .env to use it")
"""
        ),
        md("## Evaluation: base vs fine-tuned"),
        code(
            """
track_b_results = []
for _, row in eval_sample.iterrows():
    try:
        parsed = classify_via_ollama(row["text"], model="cst-diagnosis:v1")
        track_b_results.append({
            "intent_correct": parsed.get("intent") == row["intent"],
            "department_correct": parsed.get("department") == row["department"],
            "json_valid": True,
        })
    except Exception:
        track_b_results.append({"intent_correct": False, "department_correct": False, "json_valid": False})

track_b_df = pd.DataFrame(track_b_results)
track_b_summary = {
    "intent_accuracy": track_b_df["intent_correct"].mean(),
    "department_accuracy": track_b_df["department_correct"].mean(),
    "json_validity_rate": track_b_df["json_valid"].mean(),
}

comparison_md = f'''# LLM comparison: llama3.1:8b (Track A) vs cst-diagnosis:v1 (Track B)

| metric | llama3.1:8b (prompted) | cst-diagnosis:v1 (LoRA) |
|---|---|---|
| intent accuracy | {track_a_summary["intent_accuracy"]:.3f} | {track_b_summary["intent_accuracy"]:.3f} |
| department accuracy | {track_a_summary["department_accuracy"]:.3f} | {track_b_summary["department_accuracy"]:.3f} |
| JSON validity rate | {track_a_summary["json_validity_rate"]:.3f} | {track_b_summary["json_validity_rate"]:.3f} |

Rollback: set `llm_model=llama3.1:8b-instruct-q4_K_M` in `.env` (Track A) if Track B underperforms
or `cst-diagnosis:v1` is not registered.
'''
Path("evaluation/reports").mkdir(parents=True, exist_ok=True)
Path("evaluation/reports/llm_comparison.md").write_text(comparison_md, encoding="utf-8")
print(comparison_md)
"""
        ),
    ]
    nb = nbf.v4.new_notebook()
    nb["cells"] = cells
    return nb


# ---------------------------------------------------------------------------
# 05: VLM LED extraction, NOT EXECUTED in this environment (needs Ollama + llava)
# ---------------------------------------------------------------------------
def build_05_vlm_led_extraction() -> "nbf.NotebookNode":
    cells = [
        md(
            """
# 05, VLM LED extraction

**NOT EXECUTED IN THIS ENVIRONMENT**, Track B/C below need a running Ollama server with
`llava:7b` (and optionally `llava:13b`) pulled. The heuristic extractor (Track A) has no such
dependency and *could* run here, but is kept alongside the others, unexecuted, so the three-way
comparison in this notebook stays apples-to-apples in one place.

**Dataset correction (verified by inspection, not assumed):** `data/router
detection.v38-data_video.coco.zip` is a **cable/port/connector** detection dataset, categories
are `{fiber,lan,phone,power,usb} x {cable,conn}` (2137 images / 4630 boxes), not LED-colour
states. See `evaluation/datasets/roboflow_router.py`. It is used here only as a *structured hint*
source (which ports/cables are visibly connected) injected into the VLM prompt, the LED
colour/behaviour ground truth below is a small, separately hand-labelled set
(`data/processed/led_labels.jsonl`), built from `ingestion-pipeline-prototype/data/sample_images/`
plus this notebook's target of 30-60 images once more router photos are available.

**Inputs:** `data/router detection.v38-data_video.coco.zip`,
`ingestion-pipeline-prototype/data/sample_images/*.png`, `models/prompts/vlm/router_led_panel.txt`

**Outputs:** `data/processed/led_labels.jsonl`, the field-accuracy comparison table below, the
chosen `vlm_impl` + tuned prompt + confidence threshold (feeds `config/settings.yaml`).

**Pitfall:** Ollama vision needs the image as base64 **without** a `data:` prefix; a 400 "invalid
image" almost always means the prefix was left in, or the file is a PNG with an alpha channel
that PIL should have re-saved as RGB first (`libs/platform/models/vlm.py::_ensure_rgb_png_bytes`
already does this for the real adapter, this notebook's ad-hoc encoding below must too).
"""
        ),
        _SETUP_CELL,
        code(
            """
import base64
import json

from evaluation.datasets.roboflow_router import load_split

train_split = load_split("train")
print(f"{len(train_split.images)} images, {len(train_split.annotations)} boxes, categories: {list(train_split.categories.values())}")
"""
        ),
        md(
            """
## Hand-labelled LED ground truth

30-60 images hand-labelled into `data/processed/led_labels.jsonl`. This environment only has 2
router photos available (`router_red_led.png`, `router_green_led.png` in the prototype's sample
data), both labelled below as a seed; the remaining ~28-58 need real router photos, out of
scope to source here.
"""
        ),
        code(
            """
PROTOTYPE_IMAGES = Path("../ingestion-pipeline-prototype/data/sample_images")

LED_LABELS_SEED = [
    {
        "file": "router_red_led.png",
        "device_model": "unknown",
        "led_states": [{"label": "power", "colour": "red", "behaviour": "solid"}],
    },
    {
        "file": "router_green_led.png",
        "device_model": "unknown",
        "led_states": [{"label": "power", "colour": "green", "behaviour": "solid"}],
    },
]

out_path = Path("data/processed/led_labels.jsonl")
out_path.parent.mkdir(parents=True, exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    for row in LED_LABELS_SEED:
        f.write(json.dumps(row) + "\\n")
print(f"wrote {len(LED_LABELS_SEED)} seed labels to {out_path} (target: 30-60 for a full run)")
"""
        ),
        md("## Track A: heuristic HSV extractor (no Ollama needed, could run here, kept unexecuted for a fair three-way comparison)"),
        code(
            """
from libs.platform.models.vlm import HeuristicLedExtractor

heuristic = HeuristicLedExtractor()
track_a_rows = []
for label in LED_LABELS_SEED:
    path = PROTOTYPE_IMAGES / label["file"]
    if not path.exists():
        continue
    summary = heuristic.extract(path, attachment_id=label["file"], template="router_led_panel")
    predicted_colours = {led.colour for led in summary.extracted_fields.led_states}
    expected_colours = {led["colour"] for led in label["led_states"]}
    track_a_rows.append({"file": label["file"], "predicted": predicted_colours, "expected": expected_colours, "match": bool(predicted_colours & expected_colours)})

track_a_rows
"""
        ),
        md("## Track B: `llava:7b` via Ollama"),
        code(
            """
from libs.platform.models.vlm import OllamaVisionExtractor

llava_7b = OllamaVisionExtractor(base_url="http://localhost:11434", model="llava:7b")
track_b_rows = []
for label in LED_LABELS_SEED:
    path = PROTOTYPE_IMAGES / label["file"]
    if not path.exists():
        continue
    summary = llava_7b.extract(path, attachment_id=label["file"], template="router_led_panel")
    predicted_colours = {led.colour for led in summary.extracted_fields.led_states}
    expected_colours = {led["colour"] for led in label["led_states"]}
    track_b_rows.append({
        "file": label["file"], "predicted": predicted_colours, "expected": expected_colours,
        "match": bool(predicted_colours & expected_colours), "confidence": summary.confidence,
    })

track_b_rows
"""
        ),
        md("## Track C: `llava:13b` via Ollama, if it fits"),
        code(
            """
llava_13b = OllamaVisionExtractor(base_url="http://localhost:11434", model="llava:13b")
track_c_rows = []
for label in LED_LABELS_SEED:
    path = PROTOTYPE_IMAGES / label["file"]
    if not path.exists():
        continue
    try:
        summary = llava_13b.extract(path, attachment_id=label["file"], template="router_led_panel")
        predicted_colours = {led.colour for led in summary.extracted_fields.led_states}
        expected_colours = {led["colour"] for led in label["led_states"]}
        track_c_rows.append({
            "file": label["file"], "predicted": predicted_colours, "expected": expected_colours,
            "match": bool(predicted_colours & expected_colours), "confidence": summary.confidence,
        })
    except Exception as exc:
        print(f"llava:13b unavailable or failed ({exc}); skipping Track C")
        break
"""
        ),
        md(
            """
## Structured hint: injecting port/cable detections into the VLM prompt

The Roboflow dataset's real value in this pipeline is as a *pre-filter*: run a small detector
over the image first, and inject "the following ports/cables are visibly connected: ..." into
the VLM prompt, so the VLM's job narrows from "describe the whole board" to "confirm/refine what
the detector already found". A full YOLO/Detectron training run is out of scope for this
notebook; sketched below is the prompt-injection shape a trained detector's output would take.
"""
        ),
        code(
            """
def inject_structured_hint(base_prompt: str, detected_labels: list[str]) -> str:
    if not detected_labels:
        return base_prompt
    hint = "Detected on this board (from an object detector, confirm or correct): " + ", ".join(detected_labels)
    return f"{hint}\\n\\n{base_prompt}"


base_prompt = Path("models/prompts/vlm/router_led_panel.txt").read_text(encoding="utf-8")
example_hint = inject_structured_hint(base_prompt, ["power-conn", "lan-cable"])
print(example_hint[:300])
"""
        ),
        md(
            """
## Chosen configuration (to be finalised once Track B/C actually run)

Placeholder pending a real run: default to `vlm_impl=heuristic` (Track A) as the always-available
fallback per the SAD deviation table, and switch to `vlm_impl=ollama` with `llava:7b` once Track
B's field accuracy is measured to beat it on a real 30-60 image labelled set.
"""
        ),
    ]
    nb = nbf.v4.new_notebook()
    nb["cells"] = cells
    return nb


NOTEBOOKS = {
    "01_data_preparation.ipynb": build_01_data_preparation,
    "02_department_classifier.ipynb": build_02_department_classifier,
    "03_intent_and_diagnosis_llm.ipynb": build_03_intent_and_diagnosis_llm,
    "04_priority_and_sentiment.ipynb": build_04_priority_and_sentiment,
    "05_vlm_led_extraction.ipynb": build_05_vlm_led_extraction,
    "06_asr_evaluation.ipynb": build_06_asr_evaluation,
    "07_knowledge_and_graphrag.ipynb": build_07_knowledge_and_graphrag,
    "08_end_to_end_evaluation.ipynb": build_08_end_to_end_evaluation,
}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--execute", action="store_true", help="execute each notebook after writing it")
    parser.add_argument("--only", help="comma-separated notebook filenames to (re)build, default: all")
    args = parser.parse_args()

    names = args.only.split(",") if args.only else list(NOTEBOOKS.keys())

    for name in names:
        builder = NOTEBOOKS[name]
        nb = builder()
        path = _NOTEBOOKS_DIR / name
        nbf.write(nb, path)
        print(f"wrote {path}")

        if args.execute:
            from nbclient import NotebookClient

            client = NotebookClient(nb, timeout=1800, kernel_name="v1-venv", resources={"metadata": {"path": str(_NOTEBOOKS_DIR)}})
            client.execute()
            nbf.write(nb, path)
            print(f"executed {path}")


if __name__ == "__main__":
    main()
